# cert-manager API version
apiVersion: cert-manager.io/v1

# Defines a cluster-wide certificate issuer
kind: ClusterIssuer

# Name of the ClusterIssuer
metadata:
  name: letsencrypt

# ACME configuration for Let's Encrypt
spec:                                                                     # ACME configuration for the ClusterIssuer
  acme:                                                                   # Let's Encrypt ACME configuration
    email: tiagoluis.vedana@gmail.com                                     # Email for Let's Encrypt notifications 
    server: https://acme-v02.api.letsencrypt.org/directory                # Let's Encrypt staging server 
    privateKeySecretRef:                                                  # Reference to the secret containing the private key        
      name: letsencrypt                                                   # Name of the secret to store the private key
    solvers:                                                              # Solvers for ACME challenges
      - http01:                                                           # HTTP-01 challenge solver
          ingress:                                                        # Ingress configuration for the HTTP-01 challenge  
            class: nginx-ingress-controller                               # Matches ingress.className